[package]
name = "svg-hush"
version = "0.1.0"
edition = "2021"
description = "Strip scripting and other abusable features from SVG files"
categories = ["multimedia::images"]
keywords = ["xss", "sanitizer", "purify", "filter", "security"]
publish = false

[dependencies]
once_cell = "1.13.0"
quick-error = "2.0.1"
url = "2.2.2"
xml-rs = "0.8.4"
